jonjomckay/fritter

- lib/tweet.dart
- pubspec.lock
- pubspec.yaml
This should fix #2. It uses a widget that detects the direction a given string should be displayed in, and automatically changes the child widget(s) to follow that direction.
Before:
<p float="left">
</p>
After:
<p float="left">
</p>
> #2: Add support for RTL languages in tweet content

- lib/constants.dart
- lib/main.dart
- lib/options.dart
- pubspec.lock
- pubspec.yaml
This fixes #3 by adding a toggle for enabling "true black" for the dark mode theme.
Before and after:
</p>
> #3: Added support for a black theme

- lib/constants.dart
- lib/main.dart
- lib/options.dart
This adds a new option that allows the user to manually choose the app's theme. This is useful on older devices where Android might not support a native dark mode, and so the user can enable it on a per-app basis.
</p>
> Added option to set the app theme manually

- android/app/src/main/AndroidManifest.xml
- android/build.gradle
- android/gradle/wrapper/gradle-wrapper.properties
- ios/Runner/Info.plist
- lib/home/_search.dart
- lib/home/_trends.dart
- lib/home/home_screen.dart
- lib/tweet.dart
- lib/tweet/_content.dart
- pubspec.lock
- pubspec.yaml
This adds support for displaying and opening **mentions**, **hashtags** and **URLs**.
* When selecting a user mention, the user's profile is opened in a new activity.
* When selecting a hashtag, the standard search dialog is opened, and prepopulated with the hashtag (haven't worked out how to automatically search yet)
* When selecting a URL, the registered Android URL handler is opened (browser or app)
Before and after:
</p>
> Add support for linked entities (mentions, hashtags and URLs)

- fastlane/metadata/android/en-US/changelogs/next.txt
- lib/tweet.dart
- pubspec.lock
- pubspec.yaml
This fixes #40 by adding a new "Share" button to all tweets, which when tapped, will bring up a dialog where the user can choose to share the tweet's content or a link to the tweet (pointing to `twitter.com`).
</p>
> Added support for sharing tweet content and links

- fastlane/metadata/android/en-US/changelogs/next.txt
- lib/home_model.dart
- lib/tweet.dart
This adds support for displaying tweet media inside a carousel, instead of one after the other in a big column. This will save space on device screens, and give a better UX for viewing multiple images in a tweet.
Fixes #44.
Before and after:
</p>
> Now displaying tweet media in a carousel

- .github/workflows/master.yml
- .github/workflows/release.yml
- android/app/build.gradle
- android/app/src/main/AndroidManifest.xml
- android/app/src/main/kotlin/com/jonjomckay/flitter/FritterApplication.java
- fastlane/metadata/android/en-US/changelogs/hotfix.txt
- fastlane/metadata/android/en-US/changelogs/next.txt
- lib/home/home_screen.dart
- lib/main.dart
- pubspec.lock
- pubspec.yaml
This adds support for notifying the user when a new version is available. It supports both when the app is installed from F-Droid, and from GitHub.
When installed from F-Droid, tapping the notification will open the user's F-Droid client, and when installed from GitHub, the notification will download the APK directly from GitHub releases. Either way, the installation is still manual, so Fritter itself needs no extra permissions.
This fixes #65.
</p>
> Add support for update notifications

- fastlane/metadata/android/en-US/changelogs/next.txt
- lib/constants.dart
- lib/main.dart
- lib/options.dart
- lib/tweet.dart
- lib/tweet/_card.dart
This adds support for a new "Media size" option, containing multiple media sizes and an option to disable media. If media is disabled, a placeholder container is shown with a "tap to download" option.
This fixes #30.
</p>
> Add support for selecting the media size

- fastlane/metadata/android/en-US/changelogs/next.txt
- lib/client.dart
- lib/constants.dart
- lib/home/_trends.dart
- lib/home_model.dart
- lib/main.dart
- lib/ui/futures.dart
- lib/utils/cache.dart
- lib/utils/iterables.dart
- pubspec.lock
- pubspec.yaml
This adds support for being able to select a location for the trends screen. It defaults to Worldwide, and the user can select from all the locations Twitter exposes in their API.
This fixes #21.
</p>
> Add support for selecting a trend location

- lib/constants.dart
- lib/generated/l10n.dart
- lib/l10n/intl_en.arb
- lib/main.dart
- lib/settings/settings.dart
Add a new user setting to toggle update check at application startup.
This will be visible on non playstore app only.
This feature add two localized strings: `should_check_for_update_label` and `should_check_for_update_description`
Resolve issue #153 and #331
> User preferences: add a toggle to disable update check #331

- android/app/src/main/AndroidManifest.xml
Enable deeplinking for Nitter public instances URLs.
Support instances conforming to https://github.com/zedeus/nitter/wiki/Instances
Resolving issue #308
> Enable deeplinking for Nitter public instances URLs #308

- lib/tweet/_video.dart
- pubspec.lock
- pubspec.yaml
closes #398
Wake locks the screen while a video is playing and releases it when it's paused / stopped playing.
> Add Wakelock functionality while a video is playing

- lib/tweet/tweet.dart
BUG FIX [#517]: Add check in `onClickOpenTweet()` function, if tweet is a retweet. In this case it pushes now to `StatusScreen` of the original tweet and not to the retweet, as before.
> FIX [#517] show replies on retweeted tweet

- lib/tweet/tweet.dart
[#509] add check in `TweetTile` build function, whether `media` is in embedded in retweet. If this is the case `TweetMedia` will be constructed with the data from the originating tweet.
> FIX [#509] save retweeted media with originating author

- fastlane/metadata/android/en-US/changelogs/next.txt
- lib/constants.dart
- lib/group/_feed.dart
- lib/home/_saved.dart
- lib/main.dart
- lib/profile/profile.dart
- lib/search/search.dart
- lib/settings/_general.dart
- lib/tweet/_video.dart
I added one more option to the general settings tab, addressing the media:
default muting: All videos will be muted by default
This option is true by default.
In addition to that, I introduced `VideoContextState`. This class stores the user's decision to mute or unmute videos for the current feed. It works identical as the `TweetContextState`.
> add option to mute Videos by default and remember muting in feed.

- fastlane/metadata/android/en-US/changelogs/next.txt
- lib/database/entities.dart
- lib/database/repository.dart
- lib/home/_saved.dart
- lib/profile/_saved.dart
- lib/profile/profile.dart
- lib/saved/saved_tweet_model.dart
- lib/tweet/tweet.dart
[#537] Add Request: Saved tweets for profile
Add a 'Saved Tweets' tab to the `ProfileScreen`. To achieve this,  I introduced a `userId` getter to the `SavedTweet` entity, which extracts the id from the `content` property. The `ProfileSaved` tab is more or less identical to the `ProfileTweets` and `ProfileFollows` views.
> add Saved Tweets tab to ProfileScreen

- lib/tweet/tweet.dart
[#518] add `onTap` function to `_TweetTileLeading` in case of retweet. `Navigator` pushes to profile of the user who retweeted
> add navigation to profile of the person who retweeted [#518]

- lib/client.dart
the cursor from the _graphql_ _TweetDetail_ request comes from an _itemContent_ key instead of an _operation_ or _value_ key.
this should fix the bug #685.
> fix getting the cursor from the graphql TweetDetail request

- android/app/src/main/res/raw/keep.xml
This is to fix the bugs #691, #594 and #575.
When launching the app of the latest released beta version (beta8), the app crashes immediately.
Looking at the logcat output, the relevant part is:
```
05-01 15:42:49.850  4069  4069 E Icon    : Unable to load resource 0x7f040000 from pkg=com.jonjomckay.fritter
05-01 15:42:49.850  4069  4069 E Icon    : android.content.res.Resources$NotFoundException: Drawable com.jonjomckay.fritter:drawable/ic_notification with resource ID #0x7f040000
...
```
The ic_notification resource is not found on the release version.
The added keep.xml file helps fix the problem.
Reference: [Android Shrink Resources, Resource Not Found](https://shrikanth.in/android/issues/2020/07/05/shrink-resources-not-found.html).
> fix the exception of drawable/ic_notification that causes a crash at startup of the release version

- lib/client.dart
- lib/user.dart
In the response of the timeline request, the users under _globalObjects_ have a property _ext_is_blue_verified_ that tells if they have a blue check or not. (In that response, the _verified_ property of the users seems to always be _false_, so not useful).
In the response of the profile request, under _result_ there is a _is_blue_verified_ property that tells if the user has a blue check or not. (In that response, the _verified_ property under _legacy_ also seems to always be _false_, so not useful).
In the response of the graphql TweetDetail request, under _result_ there is a _is_blue_verified_ property that tells if the user has a blue check or not. (In that response, the _verified_ property under _legacy_ also seems to always be _false_, so not useful).
> fix the missing blue checks in timelines, in profile and in tweet detail

- android/app/src/main/AndroidManifest.xml
With this setting, it is possible for a user to move the app on the android smartphone's sd-card, if present.
The app is always installed in the smartphone's internal memory first. 
With this setting, a user can later choose to move the app to the smartphone's sd-card, if present, to free space on the smartphone's internal memory.
> RFE to make the app on android moveable to an sd-card

- lib/main.dart
This is to fix the bug #715.
This fixes the case of an initial link with only the username where the URI ends with /.
> fix the case of initial link where the URI ends with /

- android/app/src/main/AndroidManifest.xml
- lib/settings/_general.dart
- lib/utils/downloads.dart
This is a follow up of the [Quaker's issue #67](https://github.com/TheHCJ/Quacker/issues/67) in the case of devices with Android 11+.
This is to allow storage permission to download automatically to directory for devices with Android 11+.
> fix to allow storage permission for Android 11+

- lib/subscriptions/_import.dart
This is to fix the [Quacker issue #69](https://github.com/TheHCJ/Quacker/issues/69).
This issue also apply to Fritter.
Since the changes are not easy to view with a diff, here is the explanation of the change I made:
In subscriptions/\_import.dart file,
in the _build_ function,
Instead of:
```
return Scaffold(
...
body: Container(
```
We now have:
```
return Scaffold(
...
body: SingleChildScrollView(
child: Container(
```
> fix the textfield hidden by the keyboard in Import subscriptions page.

- android/app/src/main/kotlin/com/jonjomckay/fritter/MainActivity.kt
This is just a minor annoyance.
This fixes the black screen when the app is in recent screen mode.
Before the fix:
After the fix:
> Fix the black screen when app is in recent screen mode.
